experiment:
  model: labram         # or "eegnet"
  device: cuda          # "cuda" | "cpu" | "mps"
  n_subjects: 10       # used if data.subjects not set
  seed: 111
  epochs: 60
  optimizer: AdamW       # Adam | AdamW
  scheduler: CosineAnnealingLR   # CosineAnnealingLR | CosineAnnealingWarmRestarts | None
  # logging / checkpoints / early stopping
  log_to_wandb: true
  wandb_entity: "urban-sirca-vrije-universiteit-amsterdam"
  wandb_project: "EEG-FM"
  save_regular_checkpoints: false
  save_final_checkpoint: false
  save_best_checkpoints: false
  save_regular_checkpoints_interval: 10
  early_stopping: true
  early_stopping_patience: 10
  early_stopping_delta: 0.0
  # optional warm restarts extras
  T_0: 2
  T_mult: 2

data:
  path: data/preprocessed/KU_mi_labram_preprocessed.h5
  # subjects: [1,2,3,4,5,6,7,8,9,10]   # optional; else n_subjects used
  leave_out: [8,9]                # test set subjects
  m_leave_out:                     # optional multi-LOO size
  train_proportion: 0.9
  input_channels: 62
  num_classes: 2
  # EEGLab/Labram shaping
  n_patches_labram: 4
  patch_length: 200
  samples: 200                    # 800 for EEGNet (200 for Labram)
  electrodes:                     # optional; falls back to get_ku_dataset_channels()

meta:
  meta_batch_size: 4
  k_support: 5
  q_query: 10         # or null for “all remaining”
  inner_steps: 3
  inner_lr: 0.002
  steps_per_epoch: 2
  run_size: 100       # granularity for episode indexing

optimizations:
  use_amp: true
  use_compile: false
  non_blocking: true
  pin_memory: false

# Model-specific blocks
labram:
  lora: true
  lr: 0.001
  weight_decay: 0.0

peft_config:
  r: 1
  lora_alpha: 32
  lora_dropout: 0.5
  target_modules: ["qkv", "fc1", "proj"]

eegnet:
  lr: 0.001
  weight_decay: 0.0
  dropoutRate: 0.5
  kernLength: 64
  F1: 8
  D: 2
  F2: 16
