experiment:
  model: labram       # or "eegnet"
  device: cuda          # "cuda" | "cpu" | "mps"
  n_subjects: 54       # used if data.subjects not set
  seed: 111
  meta_iterations: 1200
  validate_every: 20
  optimizer: AdamW       # Adam | AdamW
  scheduler: CosineAnnealingLR   # CosineAnnealingLR | CosineAnnealingWarmRestarts | None
  # logging / checkpoints / early stopping
  log_to_wandb: true
  wandb_entity: "urban-sirca-vrije-universiteit-amsterdam"
  wandb_project: "EEG-FM-ABC"


  save_regular_checkpoints: true
  save_final_checkpoint: true
  save_regular_checkpoints_interval: 100
  save_best_checkpoints: true
 
  # optional warm restarts extras
  T_0: 100 
  T_mult: 2
  eta_min: 1e-5


data:
  path: data/preprocessed/KU_mi_labram_preprocessed_normalized.h5
  subjects: #[1,2,3,4]   # optional; else n_subjects used
  leave_out: [1,2,3,4,5,6]                # test set subjects
  # m_leave_out: 2                  # optional multi-LOO size
  train_proportion: 0.9
  n_channels: 62
  num_classes: 2
  # EEGLab/Labram shaping
  n_patches_labram: 4
  patch_length: 200
  samples: 800                    # 800 for EEGNet (200 for Labram) #TODO: pofukani samples
  electrodes:                     # optional; falls back to get_ku_dataset_channels()

meta:
  meta_batch_size: 12
  k_support: 5
  q_query: 160         # or null for “all remaining”
  q_eval: 160
  inner_steps: 4
  inner_lr: 1e-5
  run_size: 100       # granularity for episode indexing
  clip_grad_norm: null  # torch.nn.utils.clip_grad_norm_
  val_episodes_per_subject: 1

supervised:
  train_batch_size: 125
  eval_batch_size: 125
  n_epochs_supervised: 20
  meta_iters_per_meta_epoch: 1
  validate_meta_every: 0
  drop_last: false
  run_size: 100       # granularity for episode indexing
  clip_grad_norm: null # torch.nn.utils.clip_grad_norm_
  val_episodes_per_subject: 1

optimizations:
  use_amp: false
  use_compile: false
  non_blocking: true
  pin_memory: false

# Model-specific blocks
labram:
  lora: true
  # lr: 2e-4 
  # weight_decay: 1e-4
  lora_lr: 2e-4          
  head_lr: 5e-4          
  head_weight_decay: 5e-4
  sup_lr: 2e-4
  sup_wd: 5e-4
  adapter_checkpoint_dir: # "/home/usirca/workspace/labram-lora/weights/checkpoints/labram_lr0.002_wd0.002_AdamW_CosineAnnealingLR_191909/final_checkpoint_e60_acc0.788"

peft_config:
  r: 2
  lora_alpha: 16
  lora_dropout: 0.1
  target_modules: ["qkv", "fc1", "proj"]

eegnet:
  lr: 0.001
  weight_decay: 0.0
  dropoutRate: 0.5
  kernLength: 64
  F1: 8
  D: 2
  F2: 16
  sup_lr: 0.001
  sup_wd: 0.0
deepconvnet:
  lr: 0.001
  weight_decay: 0.0
  sup_lr: 0.001
  sup_wd: 0.001
  
test:
  n_epochs: 10
  shots: [0, 1, 2, 3, 4, 5, 10, 15, 20, 25] # number of shots for few-shot learning; if 0, will do standard testing without fine-tuning
  n_repeats: 2  # number of repeats for few-shot learning (with different random samples each time)
  models: ["labram"] # list of models to test; options are "deepconvnet", "eegnet", "labram"
  save_dir_root: "results_meta/lomso" # directory to save results and checkpoints; <experiment_name> will be replaced with the actual experiment name
